name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies for Library
      run: dotnet restore
      working-directory: src/ExcelFinancialFunctions
    - name: Build Library
      run: dotnet build --no-restore
      working-directory: src/ExcelFinancialFunctions
    - name: Restore dependencies for Tests
      run: dotnet restore
      working-directory: tests/ExcelFinancialFunctions.Tests
    - name: Build Tests
      run: dotnet build --no-restore
      working-directory: tests/ExcelFinancialFunctions.Tests
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: tests/ExcelFinancialFunctions.Tests